[2025-06-20 16:34:51,216] [ERROR] 環境変数にメールアドレスまたはパスワードがありません。
[2025-06-20 16:39:07,942] [ERROR] 環境変数にメールアドレスまたはパスワードがありません。
[2025-06-20 16:41:24,931] [ERROR] 環境変数にメールアドレスまたはパスワードがありません。
[2025-06-20 16:43:25,901] [INFO] ブラウザを閉じました
[2025-06-20 16:45:36,333] [ERROR] エラー発生
Traceback (most recent call last):
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 61, in handle_login
    go_to_login_page(driver)
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 27, in go_to_login_page
    driver.get("https://site/libecity.com/signin")
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=137.0.7151.120)
Stacktrace:
0   chromedriver                        0x0000000102cedd14 cxxbridge1$str$ptr + 2735276
1   chromedriver                        0x0000000102ce5f88 cxxbridge1$str$ptr + 2703136
2   chromedriver                        0x00000001028366f0 cxxbridge1$string$len + 90424
3   chromedriver                        0x000000010282ecc8 cxxbridge1$string$len + 59152
4   chromedriver                        0x0000000102821868 cxxbridge1$string$len + 4784
5   chromedriver                        0x0000000102823268 cxxbridge1$string$len + 11440
6   chromedriver                        0x0000000102821cbc cxxbridge1$string$len + 5892
7   chromedriver                        0x0000000102821610 cxxbridge1$string$len + 4184
8   chromedriver                        0x000000010282135c cxxbridge1$string$len + 3492
9   chromedriver                        0x000000010281f114 chromedriver + 192788
10  chromedriver                        0x000000010281fb70 chromedriver + 195440
11  chromedriver                        0x0000000102839754 cxxbridge1$string$len + 102812
12  chromedriver                        0x00000001028bfb60 cxxbridge1$string$len + 652712
13  chromedriver                        0x00000001028bf0c8 cxxbridge1$string$len + 650000
14  chromedriver                        0x0000000102871be8 cxxbridge1$string$len + 333360
15  chromedriver                        0x0000000102cb1598 cxxbridge1$str$ptr + 2487600
16  chromedriver                        0x0000000102cb4830 cxxbridge1$str$ptr + 2500552
17  chromedriver                        0x0000000102c91c14 cxxbridge1$str$ptr + 2358188
18  chromedriver                        0x0000000102cb50b8 cxxbridge1$str$ptr + 2502736
19  chromedriver                        0x0000000102c82dec cxxbridge1$str$ptr + 2297220
20  chromedriver                        0x0000000102cd5420 cxxbridge1$str$ptr + 2634680
21  chromedriver                        0x0000000102cd55ac cxxbridge1$str$ptr + 2635076
22  chromedriver                        0x0000000102ce5bd4 cxxbridge1$str$ptr + 2702188
23  libsystem_pthread.dylib             0x00000001822f2c0c _pthread_start + 136
24  libsystem_pthread.dylib             0x00000001822edb80 thread_start + 8

[2025-06-20 16:45:36,407] [INFO] ブラウザを閉じました
[2025-06-20 16:56:56,326] [ERROR] エラー発生
Traceback (most recent call last):
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 70, in handle_login
    go_to_login_page(driver)
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 36, in go_to_login_page
    driver.get("https://site/libecity.com/signin")
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=137.0.7151.120)
Stacktrace:
0   chromedriver                        0x0000000104949d14 cxxbridge1$str$ptr + 2735276
1   chromedriver                        0x0000000104941f88 cxxbridge1$str$ptr + 2703136
2   chromedriver                        0x00000001044926f0 cxxbridge1$string$len + 90424
3   chromedriver                        0x000000010448acc8 cxxbridge1$string$len + 59152
4   chromedriver                        0x000000010447d868 cxxbridge1$string$len + 4784
5   chromedriver                        0x000000010447f268 cxxbridge1$string$len + 11440
6   chromedriver                        0x000000010447dcbc cxxbridge1$string$len + 5892
7   chromedriver                        0x000000010447d610 cxxbridge1$string$len + 4184
8   chromedriver                        0x000000010447d35c cxxbridge1$string$len + 3492
9   chromedriver                        0x000000010447b114 chromedriver + 192788
10  chromedriver                        0x000000010447bb70 chromedriver + 195440
11  chromedriver                        0x0000000104495754 cxxbridge1$string$len + 102812
12  chromedriver                        0x000000010451bb60 cxxbridge1$string$len + 652712
13  chromedriver                        0x000000010451b0c8 cxxbridge1$string$len + 650000
14  chromedriver                        0x00000001044cdbe8 cxxbridge1$string$len + 333360
15  chromedriver                        0x000000010490d598 cxxbridge1$str$ptr + 2487600
16  chromedriver                        0x0000000104910830 cxxbridge1$str$ptr + 2500552
17  chromedriver                        0x00000001048edc14 cxxbridge1$str$ptr + 2358188
18  chromedriver                        0x00000001049110b8 cxxbridge1$str$ptr + 2502736
19  chromedriver                        0x00000001048dedec cxxbridge1$str$ptr + 2297220
20  chromedriver                        0x0000000104931420 cxxbridge1$str$ptr + 2634680
21  chromedriver                        0x00000001049315ac cxxbridge1$str$ptr + 2635076
22  chromedriver                        0x0000000104941bd4 cxxbridge1$str$ptr + 2702188
23  libsystem_pthread.dylib             0x00000001822f2c0c _pthread_start + 136
24  libsystem_pthread.dylib             0x00000001822edb80 thread_start + 8

[2025-06-20 16:56:56,397] [INFO] ブラウザを閉じました
[2025-06-20 16:58:08,693] [ERROR] エラー発生
Traceback (most recent call last):
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 70, in handle_login
    go_to_login_page(driver)
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 36, in go_to_login_page
    driver.get("https://site/libecity.com/signin")
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=137.0.7151.120)
Stacktrace:
0   chromedriver                        0x000000010539dd14 cxxbridge1$str$ptr + 2735276
1   chromedriver                        0x0000000105395f88 cxxbridge1$str$ptr + 2703136
2   chromedriver                        0x0000000104ee66f0 cxxbridge1$string$len + 90424
3   chromedriver                        0x0000000104edecc8 cxxbridge1$string$len + 59152
4   chromedriver                        0x0000000104ed1868 cxxbridge1$string$len + 4784
5   chromedriver                        0x0000000104ed3268 cxxbridge1$string$len + 11440
6   chromedriver                        0x0000000104ed1cbc cxxbridge1$string$len + 5892
7   chromedriver                        0x0000000104ed1610 cxxbridge1$string$len + 4184
8   chromedriver                        0x0000000104ed135c cxxbridge1$string$len + 3492
9   chromedriver                        0x0000000104ecf114 chromedriver + 192788
10  chromedriver                        0x0000000104ecfb70 chromedriver + 195440
11  chromedriver                        0x0000000104ee9754 cxxbridge1$string$len + 102812
12  chromedriver                        0x0000000104f6fb60 cxxbridge1$string$len + 652712
13  chromedriver                        0x0000000104f6f0c8 cxxbridge1$string$len + 650000
14  chromedriver                        0x0000000104f21be8 cxxbridge1$string$len + 333360
15  chromedriver                        0x0000000105361598 cxxbridge1$str$ptr + 2487600
16  chromedriver                        0x0000000105364830 cxxbridge1$str$ptr + 2500552
17  chromedriver                        0x0000000105341c14 cxxbridge1$str$ptr + 2358188
18  chromedriver                        0x00000001053650b8 cxxbridge1$str$ptr + 2502736
19  chromedriver                        0x0000000105332dec cxxbridge1$str$ptr + 2297220
20  chromedriver                        0x0000000105385420 cxxbridge1$str$ptr + 2634680
21  chromedriver                        0x00000001053855ac cxxbridge1$str$ptr + 2635076
22  chromedriver                        0x0000000105395bd4 cxxbridge1$str$ptr + 2702188
23  libsystem_pthread.dylib             0x00000001822f2c0c _pthread_start + 136
24  libsystem_pthread.dylib             0x00000001822edb80 thread_start + 8

[2025-06-20 16:58:08,858] [INFO] メッセージ送信に成功しました。
[2025-06-20 16:58:08,928] [INFO] ブラウザを閉じました
[2025-06-20 17:00:32,680] [ERROR] エラー発生
Traceback (most recent call last):
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 70, in handle_login
    go_to_login_page(driver)
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 36, in go_to_login_page
    driver.get("https://site/libecity.com/")
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=137.0.7151.120)
Stacktrace:
0   chromedriver                        0x0000000100a3dd14 cxxbridge1$str$ptr + 2735276
1   chromedriver                        0x0000000100a35f88 cxxbridge1$str$ptr + 2703136
2   chromedriver                        0x00000001005866f0 cxxbridge1$string$len + 90424
3   chromedriver                        0x000000010057ecc8 cxxbridge1$string$len + 59152
4   chromedriver                        0x0000000100571868 cxxbridge1$string$len + 4784
5   chromedriver                        0x0000000100573268 cxxbridge1$string$len + 11440
6   chromedriver                        0x0000000100571cbc cxxbridge1$string$len + 5892
7   chromedriver                        0x0000000100571610 cxxbridge1$string$len + 4184
8   chromedriver                        0x000000010057135c cxxbridge1$string$len + 3492
9   chromedriver                        0x000000010056f114 chromedriver + 192788
10  chromedriver                        0x000000010056fb70 chromedriver + 195440
11  chromedriver                        0x0000000100589754 cxxbridge1$string$len + 102812
12  chromedriver                        0x000000010060fb60 cxxbridge1$string$len + 652712
13  chromedriver                        0x000000010060f0c8 cxxbridge1$string$len + 650000
14  chromedriver                        0x00000001005c1be8 cxxbridge1$string$len + 333360
15  chromedriver                        0x0000000100a01598 cxxbridge1$str$ptr + 2487600
16  chromedriver                        0x0000000100a04830 cxxbridge1$str$ptr + 2500552
17  chromedriver                        0x00000001009e1c14 cxxbridge1$str$ptr + 2358188
18  chromedriver                        0x0000000100a050b8 cxxbridge1$str$ptr + 2502736
19  chromedriver                        0x00000001009d2dec cxxbridge1$str$ptr + 2297220
20  chromedriver                        0x0000000100a25420 cxxbridge1$str$ptr + 2634680
21  chromedriver                        0x0000000100a255ac cxxbridge1$str$ptr + 2635076
22  chromedriver                        0x0000000100a35bd4 cxxbridge1$str$ptr + 2702188
23  libsystem_pthread.dylib             0x00000001822f2c0c _pthread_start + 136
24  libsystem_pthread.dylib             0x00000001822edb80 thread_start + 8

[2025-06-20 17:00:32,840] [INFO] メッセージ送信に成功しました。
[2025-06-20 17:00:32,918] [INFO] ブラウザを閉じました
[2025-06-20 19:50:55,553] [ERROR] 要素が見つかりません
Traceback (most recent call last):
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 71, in handle_login
    input_email(driver, email)
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 39, in input_email
    driver.find_element(*LibecityElemments.EMAIL_INPUT).send_keys(email)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 914, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="eduamarty0830@gmail.com"]"}
  (Session info: chrome=137.0.7151.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x00000001046d9d14 cxxbridge1$str$ptr + 2735276
1   chromedriver                        0x00000001046d1f88 cxxbridge1$str$ptr + 2703136
2   chromedriver                        0x00000001042226f0 cxxbridge1$string$len + 90424
3   chromedriver                        0x00000001042699e0 cxxbridge1$string$len + 381992
4   chromedriver                        0x00000001042ab0c8 cxxbridge1$string$len + 650000
5   chromedriver                        0x000000010425dbe8 cxxbridge1$string$len + 333360
6   chromedriver                        0x000000010469d598 cxxbridge1$str$ptr + 2487600
7   chromedriver                        0x00000001046a0830 cxxbridge1$str$ptr + 2500552
8   chromedriver                        0x000000010467dc14 cxxbridge1$str$ptr + 2358188
9   chromedriver                        0x00000001046a10b8 cxxbridge1$str$ptr + 2502736
10  chromedriver                        0x000000010466edec cxxbridge1$str$ptr + 2297220
11  chromedriver                        0x00000001046c1420 cxxbridge1$str$ptr + 2634680
12  chromedriver                        0x00000001046c15ac cxxbridge1$str$ptr + 2635076
13  chromedriver                        0x00000001046d1bd4 cxxbridge1$str$ptr + 2702188
14  libsystem_pthread.dylib             0x00000001822f2c0c _pthread_start + 136
15  libsystem_pthread.dylib             0x00000001822edb80 thread_start + 8

[2025-06-20 19:50:55,719] [INFO] メッセージ送信に成功しました。
[2025-06-20 19:50:55,792] [INFO] ブラウザを閉じました
[2025-06-20 19:55:43,548] [ERROR] 要素が見つかりません
Traceback (most recent call last):
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 71, in handle_login
    input_email(driver, email)
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 39, in input_email
    driver.find_element(*LibecityElemments.EMAIL_INPUT).send_keys(email)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 914, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="eduamarty0830@gmail.com"]"}
  (Session info: chrome=137.0.7151.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000103251d14 cxxbridge1$str$ptr + 2735276
1   chromedriver                        0x0000000103249f88 cxxbridge1$str$ptr + 2703136
2   chromedriver                        0x0000000102d9a6f0 cxxbridge1$string$len + 90424
3   chromedriver                        0x0000000102de19e0 cxxbridge1$string$len + 381992
4   chromedriver                        0x0000000102e230c8 cxxbridge1$string$len + 650000
5   chromedriver                        0x0000000102dd5be8 cxxbridge1$string$len + 333360
6   chromedriver                        0x0000000103215598 cxxbridge1$str$ptr + 2487600
7   chromedriver                        0x0000000103218830 cxxbridge1$str$ptr + 2500552
8   chromedriver                        0x00000001031f5c14 cxxbridge1$str$ptr + 2358188
9   chromedriver                        0x00000001032190b8 cxxbridge1$str$ptr + 2502736
10  chromedriver                        0x00000001031e6dec cxxbridge1$str$ptr + 2297220
11  chromedriver                        0x0000000103239420 cxxbridge1$str$ptr + 2634680
12  chromedriver                        0x00000001032395ac cxxbridge1$str$ptr + 2635076
13  chromedriver                        0x0000000103249bd4 cxxbridge1$str$ptr + 2702188
14  libsystem_pthread.dylib             0x00000001822f2c0c _pthread_start + 136
15  libsystem_pthread.dylib             0x00000001822edb80 thread_start + 8

[2025-06-20 19:55:43,906] [INFO] メッセージ送信に成功しました。
[2025-06-20 19:55:43,980] [INFO] ブラウザを閉じました
[2025-06-20 21:22:43,222] [ERROR] 要素が見つかりません
Traceback (most recent call last):
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 71, in handle_login
    input_email(driver, email)
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 39, in input_email
    driver.find_element(*LibecityElemments.EMAIL_INPUT).send_keys(email)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 914, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="email"]"}
  (Session info: chrome=137.0.7151.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x00000001054e1d14 cxxbridge1$str$ptr + 2735276
1   chromedriver                        0x00000001054d9f88 cxxbridge1$str$ptr + 2703136
2   chromedriver                        0x000000010502a6f0 cxxbridge1$string$len + 90424
3   chromedriver                        0x00000001050719e0 cxxbridge1$string$len + 381992
4   chromedriver                        0x00000001050b30c8 cxxbridge1$string$len + 650000
5   chromedriver                        0x0000000105065be8 cxxbridge1$string$len + 333360
6   chromedriver                        0x00000001054a5598 cxxbridge1$str$ptr + 2487600
7   chromedriver                        0x00000001054a8830 cxxbridge1$str$ptr + 2500552
8   chromedriver                        0x0000000105485c14 cxxbridge1$str$ptr + 2358188
9   chromedriver                        0x00000001054a90b8 cxxbridge1$str$ptr + 2502736
10  chromedriver                        0x0000000105476dec cxxbridge1$str$ptr + 2297220
11  chromedriver                        0x00000001054c9420 cxxbridge1$str$ptr + 2634680
12  chromedriver                        0x00000001054c95ac cxxbridge1$str$ptr + 2635076
13  chromedriver                        0x00000001054d9bd4 cxxbridge1$str$ptr + 2702188
14  libsystem_pthread.dylib             0x00000001822f2c0c _pthread_start + 136
15  libsystem_pthread.dylib             0x00000001822edb80 thread_start + 8

[2025-06-20 21:22:43,375] [INFO] メッセージ送信に成功しました。
[2025-06-20 21:22:43,459] [INFO] ブラウザを閉じました
[2025-06-20 21:25:18,458] [ERROR] 要素が見つかりません
Traceback (most recent call last):
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 71, in handle_login
    input_email(driver, email)
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 39, in input_email
    driver.find_element(*LibecityElemments.EMAIL_INPUT).send_keys(email)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 914, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="email"]"}
  (Session info: chrome=137.0.7151.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102595d14 cxxbridge1$str$ptr + 2735276
1   chromedriver                        0x000000010258df88 cxxbridge1$str$ptr + 2703136
2   chromedriver                        0x00000001020de6f0 cxxbridge1$string$len + 90424
3   chromedriver                        0x00000001021259e0 cxxbridge1$string$len + 381992
4   chromedriver                        0x00000001021670c8 cxxbridge1$string$len + 650000
5   chromedriver                        0x0000000102119be8 cxxbridge1$string$len + 333360
6   chromedriver                        0x0000000102559598 cxxbridge1$str$ptr + 2487600
7   chromedriver                        0x000000010255c830 cxxbridge1$str$ptr + 2500552
8   chromedriver                        0x0000000102539c14 cxxbridge1$str$ptr + 2358188
9   chromedriver                        0x000000010255d0b8 cxxbridge1$str$ptr + 2502736
10  chromedriver                        0x000000010252adec cxxbridge1$str$ptr + 2297220
11  chromedriver                        0x000000010257d420 cxxbridge1$str$ptr + 2634680
12  chromedriver                        0x000000010257d5ac cxxbridge1$str$ptr + 2635076
13  chromedriver                        0x000000010258dbd4 cxxbridge1$str$ptr + 2702188
14  libsystem_pthread.dylib             0x00000001822f2c0c _pthread_start + 136
15  libsystem_pthread.dylib             0x00000001822edb80 thread_start + 8

[2025-06-20 21:25:18,619] [INFO] メッセージ送信に成功しました。
[2025-06-20 21:25:18,705] [INFO] ブラウザを閉じました
[2025-06-20 21:26:58,245] [ERROR] 要素が見つかりません
Traceback (most recent call last):
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 71, in handle_login
    input_email(driver, email)
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 39, in input_email
    driver.find_element(*LibecityElemments.EMAIL_INPUT).send_keys(email)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 914, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="email"]"}
  (Session info: chrome=137.0.7151.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010308dd14 cxxbridge1$str$ptr + 2735276
1   chromedriver                        0x0000000103085f88 cxxbridge1$str$ptr + 2703136
2   chromedriver                        0x0000000102bd66f0 cxxbridge1$string$len + 90424
3   chromedriver                        0x0000000102c1d9e0 cxxbridge1$string$len + 381992
4   chromedriver                        0x0000000102c5f0c8 cxxbridge1$string$len + 650000
5   chromedriver                        0x0000000102c11be8 cxxbridge1$string$len + 333360
6   chromedriver                        0x0000000103051598 cxxbridge1$str$ptr + 2487600
7   chromedriver                        0x0000000103054830 cxxbridge1$str$ptr + 2500552
8   chromedriver                        0x0000000103031c14 cxxbridge1$str$ptr + 2358188
9   chromedriver                        0x00000001030550b8 cxxbridge1$str$ptr + 2502736
10  chromedriver                        0x0000000103022dec cxxbridge1$str$ptr + 2297220
11  chromedriver                        0x0000000103075420 cxxbridge1$str$ptr + 2634680
12  chromedriver                        0x00000001030755ac cxxbridge1$str$ptr + 2635076
13  chromedriver                        0x0000000103085bd4 cxxbridge1$str$ptr + 2702188
14  libsystem_pthread.dylib             0x00000001822f2c0c _pthread_start + 136
15  libsystem_pthread.dylib             0x00000001822edb80 thread_start + 8

[2025-06-20 21:26:58,445] [INFO] メッセージ送信に成功しました。
[2025-06-20 21:26:58,534] [INFO] ブラウザを閉じました
[2025-06-20 21:28:48,207] [ERROR] 要素が見つかりません
Traceback (most recent call last):
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 71, in handle_login
    input_email(driver, email)
  File "/Users/masatakaueda/Desktop/chatwork/auto_login/flow.py", line 39, in input_email
    driver.find_element(*LibecityElemments.EMAIL_INPUT).send_keys(email)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 914, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/Users/masatakaueda/.pyenv/versions/3.12.4/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="email"]"}
  (Session info: chrome=137.0.7151.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x00000001054b1d14 cxxbridge1$str$ptr + 2735276
1   chromedriver                        0x00000001054a9f88 cxxbridge1$str$ptr + 2703136
2   chromedriver                        0x0000000104ffa6f0 cxxbridge1$string$len + 90424
3   chromedriver                        0x00000001050419e0 cxxbridge1$string$len + 381992
4   chromedriver                        0x00000001050830c8 cxxbridge1$string$len + 650000
5   chromedriver                        0x0000000105035be8 cxxbridge1$string$len + 333360
6   chromedriver                        0x0000000105475598 cxxbridge1$str$ptr + 2487600
7   chromedriver                        0x0000000105478830 cxxbridge1$str$ptr + 2500552
8   chromedriver                        0x0000000105455c14 cxxbridge1$str$ptr + 2358188
9   chromedriver                        0x00000001054790b8 cxxbridge1$str$ptr + 2502736
10  chromedriver                        0x0000000105446dec cxxbridge1$str$ptr + 2297220
11  chromedriver                        0x0000000105499420 cxxbridge1$str$ptr + 2634680
12  chromedriver                        0x00000001054995ac cxxbridge1$str$ptr + 2635076
13  chromedriver                        0x00000001054a9bd4 cxxbridge1$str$ptr + 2702188
14  libsystem_pthread.dylib             0x00000001822f2c0c _pthread_start + 136
15  libsystem_pthread.dylib             0x00000001822edb80 thread_start + 8

[2025-06-20 21:28:48,345] [INFO] メッセージ送信に成功しました。
[2025-06-20 21:28:48,427] [INFO] ブラウザを閉じました
